FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

HEALTHCHECK --interval=5s --timeout=3s \
    CMD curl --fail http://localhost/heathcheck || exit 1

WORKDIR app

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "3000"]