FROM node:20 AS build

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

COPY . /app

RUN npm run build


FROM caddy:2.8

COPY --from=build /app/dist /srv
COPY .caddy/Caddyfile /etc/caddy/Caddyfile
